# permissions for end users to edit nodegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodegroup-editor-role
rules:
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edge.harmonycloud.cn
  resources:
  - nodegroups/status
  verbs:
  - get
